---
# this docker-compose is for developing the quotes application
services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./frontend:/app
    environment:
      FLASK_ENV: development
      not_running_in_kubernetes: true # disable k8s specific functionality
      backend_host: backend
      backend_port: 5000
    restart: always
    entrypoint: # overwrite entrypoint with development flask webserver
      - flask
      - run
      - -h
      - 0.0.0.0

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8888:5000
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
      db_host: postgres
      db_port: 5432
      db_user: superuser
      db_password: complicated
      db_name: quotes
    restart: always
    entrypoint: # overwrite entrypoint with development flask webserver
      - flask
      - run
      - -h
      - 0.0.0.0

  postgres:
    container_name: postgres
    image: postgres:14.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: complicated
      POSTGRES_DB: quotes
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  # handy GUI for checking that things changed in the db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres:
