---
name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint python code
        run: bash ci/pylint.sh

      - name: Lint Dockerfiles
        run: bash ci/hadolint.sh
